### ISSUE TITLE
HttpTrait is incorrectly required on RPC protocols

### ISSUE THREAD

**Issue by dayaffe** [awslabs/aws-sdk-swift#1161]
### Describe the bug

According to Smithy docs (https://smithy.io/1.0/spec/aws/aws-json-1_1-protocol.html#supported-traits) RPC based protocols do not support HttpTrait, yet we currently require them on all protocols (https://github.com/smithy-lang/smithy-swift/blob/88529feec7b618eede831a82729f732f691e05fc/smithy-swift-codegen/src/main/kotlin/software/amazon/smithy/swift/codegen/integration/HttpBindingResolver.kt#L47).

### Expected Behavior

We should only require HttpTrait on supported protocols which includes `@restJson1` and `@restXml`.

### Current Behavior

When using a smithy file with RPC based protocols such as `@awsJson1` or `@awsJson1_1` we improperly error, forcing the user to add an HttpTrait.

### Reproduction Steps

Example Smithy File that errors:

```
namespace com.test

use aws.protocols#awsJson1_1
use aws.api#service
use aws.auth#sigv4

@awsJson1_1
@sigv4(name: "event-stream-test")
service Example {
    version: "123",
    operations: [TestStreamOperationWithInitialRequestResponse]
}

operation TestStreamOperationWithInitialRequestResponse {
    input: TestStreamInputOutputInitialRequestResponse,
    output: TestStreamInputOutputInitialRequestResponse,
    errors: [SomeError],
}

structure TestStreamInputOutputInitialRequestResponse {
    @required
    value: TestStream
    initial: String
}

@error("client")
structure SomeError {
    Message: String,
}

structure MessageWithString { @eventPayload data: String }

@streaming
union TestStream {
    MessageWithString: MessageWithString,
    SomeError: SomeError,
}
```

Example Error:
```
Oct 02, 2023 11:05:50 AM software.amazon.smithy.swift.codegen.model.AddOperationShapes$Companion execute
INFO: building unique input/output shapes for com.test#TestStreamOperationWithInitialRequestResponse

software.amazon.smithy.model.node.ExpectationNotMetException: Expected shape `com.test#TestStreamOperationWithInitialRequestResponse` to have a trait `software.amazon.smithy.model.traits.HttpTrait` (/Users/dayaffe/Documents/Development/SwiftSDKWorkspace/smithy-swift/smithy-swift-codegen/build/resources/test/event-stream-initial-request-response.smithy [14, 1])
	at app//software.amazon.smithy.model.shapes.Shape.lambda$expectTrait$0(Shape.java:332)
	at java.base@17.0.8/java.util.Optional.orElseThrow(Optional.java:403)
	at app//software.amazon.smithy.model.shapes.Shape.expectTrait(Shape.java:332)
	at app//software.amazon.smithy.swift.codegen.integration.HttpTraitResolver.httpTrait(HttpBindingResolver.kt:47)
	at app//software.amazon.smithy.swift.codegen.integration.HttpBindingProtocolGenerator.getHttpBindingOperations(HttpBindingProtocolGenerator.kt:488)
	at app//software.amazon.smithy.swift.codegen.integration.HttpBindingProtocolGenerator.initializeMiddleware(HttpBindingProtocolGenerator.kt:424)
	at app//HttpProtocolClientGeneratorTests.setupTests(HttpProtocolClientGeneratorTests.kt:162)
	at app//HttpProtocolClientGeneratorTests.it renders client initialization block for event streaming(HttpProtocolClientGeneratorTests.kt:13)
	at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
``` 

This same file works by adding `@http(method: "POST", uri: "/example")` to the operation.

### Possible Solution

Only apply this expectation if the protocol supports it.

### Additional Information/Context

We may also discover additional areas where we improperly call classes RestX when they actually use RPCx or apply checks which do not belong on all protocols.

### AWS SWIFT SDK version used

latest

### Compiler and Version used

latest

### Operating System and version

latest

**Comment by dayaffe** [comment]
Effort is for investigation. We are not currently sure why we haven't seen errors during codegen for the 300+ supported AWS services.

**Comment by dayaffe** [comment]
Issue is contained to our testing setup. Will take up being able to have protocol-specific tests when needed in other issues.
