### ISSUE TITLE
Preview build failure on artifact copy

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1685]
### Describe the bug

Preview build sometimes fails with an error such as:
```
{
  "errorType": "Error",
  "errorMessage": "failed to download: {\"Bucket\":\"swiftcatapultpipelineswift-catapultbucket7b6ea89c-egq9i9t3ch4b\",\"Key\":\"artifact/2024/08/15/preview/a8cb04c8-62dd-4c1c-8595-11527e000ae2/GenerateSDKCodeBuildStepCodeBuildStepCodeBuildOutput.zip\"}",
  "trace": [
    "Error: failed to download: {\"Bucket\":\"swiftcatapultpipelineswift-catapultbucket7b6ea89c-egq9i9t3ch4b\",\"Key\":\"artifact/2024/08/15/preview/a8cb04c8-62dd-4c1c-8595-11527e000ae2/GenerateSDKCodeBuildStepCodeBuildStepCodeBuildOutput.zip\"}",
    "    at _S3Client.downloadObjectToStream (/var/task/index.js:98391:17)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "    at async loadCodeBuildOutput (/var/task/index.js:158328:18)",
    "    at async Runtime.handler (/var/task/index.js:158289:18)"
  ]
}
```

### Expected Behavior

Preview builds should always copy artifacts from previous build steps successfully.

### Current Behavior

Intermittently, preview builds fail with an error similar to above.

### Reproduction Steps

Review logs for previous preview builds

### AWS SWIFT SDK version used

main

### Compiler and Version used

N/A

### Operating System and version

N/A

**Comment by sichanyoo** [comment]
Moved to 2162
